name: First workflow
on:
  push:
    branches: main
  workflow_dispatch:
    inputs:
      homedrive:
        description: 'The home drive on the machine'
        required: true
      logLevel:
        description: 'Log level'
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tag:
        description: 'Apply tag after successfull test run'
        required: true
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        options:
          - stage
          - prod
          - oldstable
jobs:
  FirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hi!"
      - name: Checkout
        uses: actions/checkout@4.2.2
      - name: List files
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
          
